
gPokeNewsTextGameCorner_Upcoming::
	.string "Greetings!\n"
	.string "It's time for POKéMON NEWS.\p"
	.string "It's approaching!\n"
	.string "It's finally coming!\p"
	.string "The GAME CORNER's service day will be\n"
	.string "here in just this many days: {STR_VAR_1}!\p"
	.string "Even those who are usually unlucky\n"
	.string "may be lucky on this particular day!\p"
	.string "That's the news on POKéMON NEWS.$"

gPokeNewsTextGameCorner_Ongoing::
	.string "Greetings!\n"
	.string "It's time for POKéMON NEWS.\p"
	.string "It's here!\n"
	.string "It's finally arrived!\p"
	.string "GAME CORNER's service day has finally\n"
	.string "arrived!\p"
	.string "Could you be lucky at the SLOTS \n"
	.string "and ROULETTE?\p"
	.string "The location is MAUVILLE CITY.\n"
	.string "This is the place!\p"
	.string "That's the news on POKéMON NEWS.$"

gPokeNewsTextGameCorner_Ending::
	.string "Greetings!\n"
	.string "It's time for POKéMON NEWS.\p"
	.string "It's here!\n"
	.string "It's finally arrived!\p"
	.string "GAME CORNER's service day has finally\n"
	.string "arrived!\p"
	.string "Could you be lucky at the SLOTS\n"
	.string "and ROULETTE?\p"
	.string "Time is limited and has almost run out.\n"
	.string "The location is MAUVILLE CITY.\p"
	.string "That's the news on POKéMON NEWS.$"

